### ISSUE TITLE
Pull changes and rebase

### ISSUE THREAD

**Issue by inglor** [eli-schwartz/pkgbuilds#9]
Hi there,

As I'm not an expect on subtrees I'm trying to understand how to get the changes from AUR 

    aurpublish -p PACKAGE
and do a rebase on the same time.

Currently when I do a aurpublish -p PACKAGE on [my repo] it says my repo is 184 commits ahead after which I don't get.

The reason for all of these is that currently the github repo is about 2 commits behind the AUR and trying to update a local copy (different pc) prior of doing a package update.

[my repo]: https://github.com/inglor/pkgbuild-super

**Comment by eli-schwartz** [comment]
I guess... don't rebase? subtrees don't really work that way AFAIK. I just pull the changes first. :smile:
I'm not sure how you'd get that complaint either...

Anyway, looks like you did figure it out, as all your packages in that repo seem to be uploaded and you have committed since you opened this.

**Comment by inglor** [comment]
I did indeed updated the package but was curious to see why I get all these merges - is this normal with subtrees?

**Comment by eli-schwartz** [comment]
Yes. Subtrees are internally represented by merging with --allow-unrelated-histories to copy files into a subdirectory, with some hackish parsing of the logs for magic keywords in the commit message to detect already-split history. That's why your history will actually show PKGBUILD files at the repository root. You can look at the implementation in `/usr/lib/git-core/git-subtree`, it's all shellscript. :smile:
